const FETCH_ALL_REGIONS = {
  REQUESTED: "FETCH_ALL_REGIONS_REQUESTED",
  SUCCEEDED: "FETCH_ALL_REGIONS_SUCCEEDED",
  FAILED: "FETCH_ALL_REGIONS_FAILED",
};

const SEARCH_REGION = {
  REQUESTED: "SEARCH_REGION_REQUESTED",
  SUCCEEDED: "SEARCH_REGION_SUCCEEDED",
  FAILED: "SEARCH_REGION_FAILED",
  CLEAN: "SEARCH_REGION_CLEAN",
};

const HANDLE_DRAWER = "HANDLE_DRAWER";

export { FETCH_ALL_REGIONS, SEARCH_REGION, HANDLE_DRAWER };
